tab_spaces = 2
max_width = 120
ideal_width = 120
where_trailing_comma = false
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
enum_trailing_comma = false
match_block_trailing_comma  = false
match_wildcard_trailing_comma = false
